/*
 * File: app/model/Eventlog.js
 *
 * This file was generated by Sencha Architect version 4.2.3.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 6.5.x Classic library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 6.5.x Classic. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('EventLog.model.Eventlog', {
    extend: 'Ext.data.Model',

    requires: [
        'Ext.data.field.Date',
        'Ext.data.field.String'
    ],

    fields: [
        {
            type: 'date',
            name: 'time',
            dateReadFormat: 'timestamp'
        },
        {
            type: 'string',
            name: 'detail'
        },
        {
            convert: function(v, rec) {
                return rec.data.class;
            },
            name: 'class_name'
        },
        {
            name: 'state_type'
        },
        {
            name: 'type'
        },
        {
            name: 'name'
        },
        {
            name: 'state'
        }
    ]
});