/*
 * File: app/view/indexViewController.js
 *
 * This file was generated by Sencha Architect version 4.2.3.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 6.5.x Classic library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 6.5.x Classic. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('EventLog.view.indexViewController', {
    extend: 'Ext.app.ViewController',
    alias: 'controller.index',

    loadData: function() {
        clearTimeout(this.requestTime);

        var store = Ext.getStore("Eventlog");

        var filters = this.getFilters();

        store.getProxy().extraParams.filters = JSON.stringify(filters);
        store.reload();

        if (Number(this.getViewModel().data.refreshTime) === Infinity) {
            return ;
        }

        this.requestTime = setTimeout(this.loadData.bind(this), this.getViewModel().data.refreshTime);
    },

    getFilters: function() {
        var filterData = this.getViewModel().data.filter || {};

        return Object.keys(filterData).reduce(function(result, key) {
            if (filterData[key] === null || filterData[key] === undefined || filterData[key].length === 0) {
                return result;
            }

            var newFilter = {};
            newFilter[key] = filterData[key];
            return Ext.apply({}, result, newFilter);
        }, {});
    },

    saveFilter: function(fn) {
        var filters = this.getFilters();

        window.history.pushState(null, null, "?filters=".concat(JSON.stringify(filters)));

        fn();
    }

});
