/*
 * File: app/view/indexViewModel.js
 *
 * This file was generated by Sencha Architect version 4.2.3.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 6.5.x Classic library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 6.5.x Classic. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('EventLog.view.indexViewModel', {
    extend: 'Ext.app.ViewModel',
    alias: 'viewmodel.index',

    data: {
        filter: {
            start_time: Math.floor(createYestardayDate()/ 1000),end_time: Math.floor(new Date().getTime()/ 1000),servicegroup_name: null, state_type: null, details: null, class: null, host_name: null, hostgroup_name: null, service_description: null, state: [
                
            ]
        }, refreshTime: 10000
    }

});